name = "Taako"
race = "Elf"
subrace = "High Elf"
class = "Wizard"
subclass = "Transmutation"

[proficiencies]
skills = ["Arcana", "Insight"]

[Inventory]
weapons = ["Rapier"]
armor = ["Padded Armor"]
items = ["Amulet"]

[spells]
level = [
    ["Fire Bolt", "Acid Splash"],    # Cantrip
    ["Alarm", "Identify", "Shield"], # Level 1
    ["Blur", "Continual Flame"],     # Level 2
    [],                              # Level 3
    [],                              # Level 4
    [],                              # Level 5
    [],                              # Level 6
    [],                              # Level 7
    [],                              # Level 8
    [],                              # Level 9
]
